### ISSUE TITLE
pod 'HotmobiOSSDK', pod install asking for a password

### ISSUE THREAD

**Issue by dklt** [hotmobmobile/hotmob-ios-sdk#38]
Is it normal ?

 >>> pod install
Analyzing dependencies
Downloading dependencies
Installing Alamofire (5.1.0)
Installing Differentiator (4.0.1)
Installing HotmobiOSSDK (5.3.0)
Username for 'https://gitlab.com': 
Password for 'https://gitlab.com': 

[!] Error installing HotmobiOSSDK
[!] /usr/bin/git clone https://gitlab.com/hotmob-sdk/ios-sdk.git /var/folders/xm/6bszhzvd6djfh2vqk_91pt2xphsg7y/T/d20200421-49224-1gzrukq --template= --single-branch --depth 1 --branch 5.3.0

Cloning into '/var/folders/xm/6bszhzvd6djfh2vqk_91pt2xphsg7y/T/d20200421-49224-1gzrukq'...
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.com/hotmob-sdk/ios-sdk.git/'

**Comment by dklt** [comment]
ref :: >>> If you're using HTTPS, check to make sure that your URL is correct. For example:...(sniped)
ref2 :: >>> git clone https://gitlab.com/hotmob-sdk/ios-sdk.git
ref3 :: >>> git clone https://github.com/hotmobmobile/hotmob-ios-sdk.git (correct one)
ref4 :: >>> pod search "HotmobiOSSDK"
-> HotmobiOSSDK (5.3.0)
   HotmobiOSSDK version: 5.3.0
   pod 'HotmobiOSSDK', '~> 5.3.0'
   - Homepage: https://gitlab.com/hotmob-sdk/ios-sdk
   - Source:   https://gitlab.com/hotmob-sdk/ios-sdk.git

**Comment by hotmob-kenwong** [comment]
Yes, it is normal. Our SDK is hosted on a private repository. Please contact our staff and send your GitLab account in order to install the SDK.
